<?php
	session_start();
	session_regenerate_id(true);
	unset($_SESSION['project_id']);
	unset($_SESSION['project_name']);
	unset($_SESSION['project_email']);
	unset($_SESSION['project_mobile']);
	session_destroy();
	header("location:index.php");
?>